"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
from pathlib import Path
import os
import environ
# from authlib.jose import JsonWebKey

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)

# reading .env file
# The .env file should be in the project root, alongside manage.py
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

# False if not set in os.environ
DEBUG = env('DEBUG') 

# Raises Django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'helseid'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



def get_helseid_private_key():
    with open(BASE_DIR.parent / 'private_key.json', 'r') as f:
        text = f.read()
        private_key_dict = json.loads(text)
        return private_key_dict

HELSEID_DUMMY_SERVER_METADATA_PATH = BASE_DIR.parent / 'dummy_server_metadata.json'

HELSEID_CLIENT_ID = env('HELSEID_CLIENT_ID')
HELSEID_CLIENT_SECRET = get_helseid_private_key()
HELSEID_SERVER_METADATA_URL = "https://helseid-sts.test.nhn.no/.well-known/openid-configuration"

# AUTHLIB_OAUTH_CLIENTS = {
#     'helseid': {
#         # Konfigurasjon for Private Key JWT
#         'token_endpoint_auth_method': 'private_key_jwt',
#         'client_auth_method': 'private_key_jwt',
        
#         # Funksjonen som returnerer din private nøkkel
#         'client_assertion_signing_key': get_helseid_private_key,
        
#         # Algoritmen du bruker (HelseID støtter RS256)
#         'client_assertion_signing_alg': 'RS256',
        
#         # Scopes du trenger. 'openid' og 'profile' er standard.
#         # Du må ofte ha PID eller HPR-nummer også.
#         'client_kwargs': {
#             'scope': 'openid profile helseid://scopes/identity/pid',
#             'code_challenge_method': 'S256',  # PKCE er påkrevd av HelseID
#         }
#     }
# }